const NUMBER_OF_COHORTS = 10;
const NUMBER_OF_STUDENTS_BY_COHORT = 150;

const NUMBER_OF_TITLES = 10;
const NUMBER_OF_PROFESSORS = 100;
const NUMBER_OF_STUDENTS = 1000;

module.exports = {
    NUMBER_OF_COHORTS,
    NUMBER_OF_STUDENTS_BY_COHORT,
    
    NUMBER_OF_TITLES,
    NUMBER_OF_PROFESSORS,
    NUMBER_OF_STUDENTS
}
